= Learning project for lazy viewing files on the sofa :)

== Description

This simple flask project makes it eay to view photos from one your device to all other devices in the house

NOTE: This is my local learning project, so it is with debug mode and just for local using (for a while:)

== Installation

=== Select host

Select some host for your project (e.g. `192.168.x.x`)

=== Install docker

Install docker and docker-compose as says in official docker site

=== Install the project to some dir you choose

Create directory, clone the project and install needed libraries

[source, bash]
----
cd ~
mkdir photos_view
cd photos_view
git clone git@github.com:tol2000/simply_dir_viewer.git .
mkdir public_files
----

=== Set public folder for photos

By default you will see all photos from `public_files` subdir of your project (you just created it above).

If you want, you may set another folder. Just edit `docker-compose.yaml` and set appropriate volume mapping
in service app (set your dir before ":")
[source]
----
volumes:
  - /your_dir_of_public_files:/public_files
----

=== Run project


.In project dir run
[source, bash]
----
docker-compose up -d
----

=== Stop project

.In project dir run
[source, bash]
----
docker-compose down
----

=== View photos from any device

Enjoy by view all your photos in `public_files` from any device by following link:
link:http://192.168.x.x:8080[]
