= Learning project for lazy viewing files on the sofa :)

== Description

This simple flask project makes it eay to view photos from one your device to all other devices in the house

NOTE: This is my local learning project, so it is with debug mode and just for local using (for a while:)

NOTE: I described the installation process for my OS (Fedora), you may easily
      adopt it for you OS without any problems, I hope :)

== PreInstallation

=== Select host

Select some host for your project (e.g. `192.168.x.x`)

=== Install the project to some dir you choose

Create directory and clone the project

[source, bash]
----
cd ~
mkdir photos_view
cd photos_view
git clone git@github.com:tol2000/simply_dir_viewer.git .
mkdir public_files
----

=== Set public folder for display

By default you will see all photos from `public_files` subdir of your project
(you just created it above).
If you want, you may set another folder, see `SIMPLY_DIR_VIEWER_PUBLIC_FILES`
environment variable in "Project settings" chapter.

== Install with docker (simpler for who knows docker)

=== Install docker

Install docker and docker-compose as says in official docker site

=== Build project

.In project dir run the code below and wait for the container build
[source, bash]
----
docker-compose build
----

=== Run project

.In project dir run the code below
[source, bash]
----
docker-compose up -d
----

=== Stop project

.In project dir run the code below
[source, bash]
----
docker-compose down
----

== Install without docker (using python)

=== Install python 3, it's pip and pipenv

[source, bash]
----
sudo dnf install python3
sudo dnf install python3-pip
pip install pipenv
----

=== Run project

[source, bash]
----
pipenv run python simply_dir_viewer.py
----

== View photos from any device

Enjoy by view all your photos in `./public_files` (or any other folder you set)
from any device by following the link:
link:http://192.168.x.x:8080[]

== Project settings

You can manage some project settings like below

=== Environment variables

In linux you may set it through `export` command and in Windows you can use `set` command.

* SIMPLY_DIR_VIEWER_PUBLIC_FILES -
  Root folder to display your photos and other supported files
* SIMPLY_DIR_VIEWER_SUFFIXES_TO_DISPLAY -
  Comma separated list of file extensions to display in project (with leading dot). +
  Default: `.jpg, .jpeg, .png, .heif, .heic`

=== Other notes

==== .HEIF (.HEIC) support

* If you want to see .HEIF (.HEIC) files from apple, on linux you may install the package
  `qt-heif-image-plugin`
