= Learning project for lazy viewing files on the sofa :)

== Description

This simple flask project makes it eay to view photos from one your device to all other devices in the house

NOTE: This is my local learning project, so it is without any docker wraps and debug mode is present, so it's just for local using (for a while:)

== Installation

=== Select host

  Select some host for your project (e.g. `192.168.x.x`)

=== Install python 3 and it's pip

[source, bash]
----
sudo dnf install python3
sudo dnf install python3-pip
----

=== Install the project to some dir you choose

Create directory, clone the project and install needed libraries

[source, bash]
----
cd ~
mkdir photos_view
cd photos_view
mkdir public_files
git clone git@github.com:tol2000/simply_dir_viewer.git .
python -m pip install -r requirements.txt
----

=== Public folder for photos

By default you will see all photos from `public_files` subdir of your project (you just created it above).

If you want, you may set another folder in environment variable `SIMPLY_DIR_VIEWER_PUBLIC_FILES`

=== Run project

[source, bash]
----
python simply_dir_viewer.py
----

=== View photos from any device

Enjoy by view all your photos in `public_files` from any device by following link:
link:http://192.168.x.x:8080[]

